# -*- coding: utf-8 -*-
"""instagram_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l0GHJ1p8TnxNgEJdD4pfnsDhBaKKMTZJ
"""

!pip install  instagram-scraper

!pip uninstall instagram-scraper

!pip install instagram-scraper==1.7.0

instagram-scraper _mariebetsy_ -m 500 #to scrape the username  images and videos

instagram-scraper fashionshows --tag  #to scrape all images and videos under an hashtag

instagram-scraper _mariebetsy_ -t image -m 500 #to scrape 500 images in this profile

